# Generated by Django 5.2.4 on 2025-07-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
