# Generated by Django 5.2.4 on 2025-07-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0003_alter_custom_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Image',
            field=models.ImageField(default='NO picture added', null=True, upload_to='blog/'),
        ),
    ]
