# Generated by Django 5.2.4 on 2025-08-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms', '0008_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
